### ISSUE TITLE
Internal Exception: io.netty.handler.codec.DecoderException: io.netty.handler.codec.EncoderException: java.io.IOException: Root tag must be a named compound tag

### ISSUE THREAD

**Issue by mkhell7518** [bigchadguys/bcgplus#1]
Unable to use BCG+ with MCProHosting, not sure if I'm doing something wrong but I continue to get this error when I try to get in...

Internal Exception: io.netty.handler.codec.DecoderException: io.netty.handler.codec.EncoderException: java.io.IOException: Root tag must be a named compound tag

Any thoughts?

**Comment by jflec** [comment]
Double check your versions are matching and make sure your Fabric loader is 0.14.25.
