### ISSUE TITLE
inventory problem with compact storage

### ISSUE THREAD

**Issue by DynuKin** [bigchadguys/bcgplus#10]
compact-storage-1.20.1-fabric-6.0.1.62 I don't know if there are big compatibility issues with updating, but there is kind of a big issue with the current version of compact storage in this modpack, below is what I was told to do to fix but it is not my server so I dont really know what to do about it.

"Chest / Barrel contents are removed when dying to a different colour, please update to 6.1"

**Comment by jflec** [comment]
Assuming this is for BCG+ NC, going to be fixed tomorrow.
