### ISSUE TITLE
End crystals respawning in the wrong place

### ISSUE THREAD

**Issue by Funny-Monkey98** [bigchadguys/bcgplus#13]
Version: BigChadGuys Plus-1.1.17 / BigChadGuys Plus (w cobblemon)

Mods: YUNG's Better End Island
           Savage Ender Dragon

Behaviour: During the End Dragon battle, end crystals respawn at the correct position but the wrong y level.
                  Probably due to the crystal respawn mechanic of Savage Ender Dragon using the position of the vanilla pillars, which 
                  causes the crystals to respawn inside or above the pillars generated by YUNG's Better End Island

![image](https://github.com/bigchadguys/bcgplus/assets/168900055/63f9d974-5a01-4e71-9159-6a11a91ccff3)

Haven't seen this reported anywhere but this made the dragon fight near-impossible on our server :(

**Comment by jflec** [comment]
So sorry to hear about this! Definitely makes the fight harder 😭 Will try to replicate the issue and find a fix by next update. 🫡
