### ISSUE TITLE
Login Crash for BCG Plus Servers

### ISSUE THREAD

**Issue by NightingaleZK** [bigchadguys/bcgplus#17]
Never experienced this before; took a break from Minecraft for two weeks and this happens. 
![Screenshot 2024-05-22 000909](https://github.com/bigchadguys/bcgplus/assets/37088272/9ac11712-fece-404b-9c37-77968bbf377b)

**Comment by jflec** [comment]
Typically means there is a version mismatch between you and the server, I'd recommend ensuring you're on the same versions.
