### ISSUE TITLE
Error Message When Trying To Join A Multiplayer

### ISSUE THREAD

**Issue by YemNem** [bigchadguys/bcgplus#19]
Whenever I try to join a multiplayer world it puts a big wall of text up, and it can't even show the entire message.
![image](https://github.com/bigchadguys/bcgplus/assets/170773863/31e38669-f02a-4b87-8eb9-776f6f20980b)

**Comment by jakesavi** [comment]
New Update causes this issue. Server has updated to newer version. Please update your version to fix his issue.
