### ISSUE TITLE
Wrong file name for Fabric jar file in start.sh

### ISSUE THREAD

**Issue by jakesavi** [bigchadguys/bcgplus#20]
start.sh contains the incorrect file for fabric-server-launcher.jar, instead contains "fabric-server-launch.jar" leading to: ``` "Error: Unable to access jarfile fabric-server-launch.jar"```

**Comment by jakesavi** [comment]
I'm gunna be honest. This gave me a headache for exactly 12 minutes. Until I actually read the file name.

**Comment by jflec** [comment]
Thanks for letting me know! Had to flip around some files due to the Fabric loader update, I'll get these sorted next update!
