### ISSUE TITLE
[2.0.1] Diary task for Skills in the Introduction tab has broken links to other tasks

### ISSUE THREAD

**Issue by Joorren** [bigchadguys/bcgplus#21]
![image](https://github.com/bigchadguys/bcgplus/assets/22602428/4cc2351e-529c-4b8a-ba26-50b17634b746)

* Clicking the "Exploration" link, nothing happens.

* Clicking the "Fishing Collection" link, gives the following error:
![image](https://github.com/bigchadguys/bcgplus/assets/22602428/439af7e3-1a7b-4b2d-b7cf-cc6d2309c9ef)

**Comment by jflec** [comment]
Thank you for the heads up! Super odd that I missed these since I specifically remember setting them. 'Tis the joy of modpack development. 😅

Will fix next update! 🫡
