### ISSUE TITLE
Recipe Conflict between Create Deco and Create Crafts and Additions.

### ISSUE THREAD

**Issue by MisterGaming3** [bigchadguys/bcgplus#22]
Steps to reproduce:
1. Run a [Create] Zinc Ingot through the mechanical press
2. Mechanical Press creates the [Create Deco] Zinc Sheet
3. [Create Deco] Zinc Sheet cannot be used to craft items like the [Create: Crafts and Additions] Capacitor
4. [Create Crafts and Additions] Zinc Sheet is unable to be acquired

Simple fix would probably be to just make all the recipes in Create Deco and Create Crafts and Additions able to use either sheet interchangeably.

**Comment by MisterGaming3** [comment]
The main effect of this is that capacitors are uncraftable, which completely locks you out of the accumulator, alternator, motor, and tesla coil. Was really hoping to light up my streets with the light bulbs from this mod.

**Comment by jflec** [comment]
Should be fixed, if you're on the latest and it isn't, make sure you've got the BCG+ Data Pack installed, sometimes installations break.
