### ISSUE TITLE
Console Output Spam: Cobblemon Issue

### ISSUE THREAD

**Issue by SolarRadiation** [bigchadguys/bcgplus#23]
Please see an example of the below dedicated server console output:

> [19:02:26] [Worker-Main-3/WARN]: Empty or non-existent pool: cobblemon:ruins/cave_support
> [19:04:02] [Worker-Main-11/WARN]: Empty or non-existent pool: cobblemon:ruins/cave_support
> [19:04:06] [Worker-Main-12/WARN]: Empty or non-existent pool: cobblemon:ruins/cave_support
> [19:04:06] [Worker-Main-12/WARN]: Empty or non-existent pool: cobblemon:cobblemon_caves
> [19:04:06] [Worker-Main-12/WARN]: Empty or non-existent pool: cobblemon:cobblemon_caves
> [19:04:06] [Worker-Main-12/WARN]: Empty or non-existent pool: cobblemon:cobblemon_caves
> [19:04:06] [Worker-Main-12/WARN]: Empty or non-existent pool: cobblemon:cobblemon_caves
> [19:04:06] [Worker-Main-12/WARN]: Empty or non-existent pool: cobblemon:cobblemon_caves
> [19:04:06] [Worker-Main-12/WARN]: Empty or non-existent pool: cobblemon:cobblemon_caves
> [19:04:06] [Worker-Main-12/WARN]: Empty or non-existent pool: cobblemon:cobblemon_caves
> [19:05:03] [Worker-Main-3/WARN]: Empty or non-existent pool: cobblemon:ruins/cave_support
> [19:05:19] [Worker-Main-11/WARN]: Empty or non-existent pool: cobblemon:cobblemon_caves
> [19:05:19] [Worker-Main-11/WARN]: Empty or non-existent pool: cobblemon:cobblemon_caves
> [19:05:19] [Worker-Main-11/WARN]: Empty or non-existent pool: cobblemon:cobblemon_caves
> [19:05:19] [Worker-Main-11/WARN]: Empty or non-existent pool: cobblemon:cobblemon_caves
> [19:05:19]  [Worker-Main-11/WARN]: Empty or non-exi[19:05:19]  [Worker-Main-11/WARN]: Empty or non-existent pool:  cobblemon:cobblemon_caves
> [19:05:19] [Worker-Main-11/WARN]: Empty or non-existent pool: cobblemon:cobblemon_caves
> stent pool: cobblemon:cobblemon_caves

This is an issue as it is spamming the console. This is a fresh installed of a dedicated BCG Plus server on MineOS (Debian Linux (yes I know, outdated)) running on Java 17.0.9.

If this is specifically an issue with Cobblemon instead, please let me know so I can submit an issue for their mod instead.

Regards,

- SolarRadiation

**Comment by jflec** [comment]
They are just warnings gameplay wise you'll be good, you can disable any console logs by going into the Log Begone config file and adding them as an entry. I'd use something like "Empty or non-existent" to grab them all.
