### ISSUE TITLE
Selling Bin clearing on server restart

### ISSUE THREAD

**Issue by GarthF** [bigchadguys/bcgplus#24]
I'm hosting an instance of BFG Plus with Cobblemon, 2.0.1 on pebblehost.

I noticed this morning after storing items in the Wooden Selling Box that all items inside the box were erased (including 40 or so emeralds). 

The pebble server restarts itself overnight each day, so I decided to run a test. Put a tomato in the box, rebooted the server myself. Tomato is erased.

**Comment by GarthF** [comment]
As a side note, tested this in a single player world and the box retained its contents.

**Comment by jflec** [comment]
I'll be rewriting Selling Bin soon, will make sure to squash this bug when I do, thank you for the report!
