### ISSUE TITLE
Bug: All Cobblemon spawn in PC and crashes the game

### ISSUE THREAD

**Issue by Emeria-Val** [bigchadguys/bcgplus#27]
Been playing on a private server for this modpack over the last week.
Today a bug started where ALL Cobblemon possible spawn in the PC at level 10 alongside all of their evolutions.
As soon as you hit Page 8 in the PC it causes a full crash to desktop. Digging around in the Crash logs seems to point towards some sort of Memory Leak issue regarding the Pokemon "Smeargle". I've asked in the Cobblemon server and they've effectively said "it's not our issue, it's an addon issue because of Smeargle."
So I'm asking here as I'm at a loss of what to do. No amount of server restarting has fixed the issue at all. The PC is unusable as a result of this...

[crash-2024-06-15_01.36.18-client.txt](https://github.com/user-attachments/files/15846382/crash-2024-06-15_01.36.18-client.txt)
[crash-2024-06-15_01.48.52-client.txt](https://github.com/user-attachments/files/15846383/crash-2024-06-15_01.48.52-client.txt)
[crash-2024-06-15_10.24.47-client.txt](https://github.com/user-attachments/files/15846384/crash-2024-06-15_10.24.47-client.txt)
![image](https://github.com/bigchadguys/bcgplus/assets/172893282/4c0e6be0-2a11-4e0a-b30c-78e4b4d8dab5)

**Comment by jflec** [comment]
I will send this report to the proper addon developer, it might have already been fixed.
