### ISSUE TITLE
Minecraft Texture issue

### ISSUE THREAD

**Issue by vampuurr** [bigchadguys/bcgplus#28]
This has happened to 2 of my friends whilst hosting that their Minecraft textures turn into black and purple squares and when they rejoin it crashes their game however once they reload Minecraft and then rejoin its all okay the only other thing we have added into this modpack is essential is that the issue?

**Comment by jflec** [comment]
Essential *could* be the issue, I would join the Discord to submit a bug report: https://discord.gg/bigchadguys
