### ISSUE TITLE
Random freezing frames

### ISSUE THREAD

**Issue by LordScreem** [bigchadguys/bcgplus#3]
Every few seconds, the game freezes for about 0,5s - 1s.  There are less freezes if I stand still and more when I try to explore the world. I think there are some issues with the chunk loading. I tried to change every setting but without any improvements. I am using the default Java version that comes with the modpack / curseforge and I set the RAM to 8GB. Changing any video settings ingame did not help nor turning the shaders off. This issue only occures with BCG+. Other modpacks with 250+ mods run smoothly with about 60-100 fps.

**Comment by jflec** [comment]
Open up a ticket in the Discord: discord.gg/bigchadguys it'll be much easier to help you there.

This issues page is dedicated towards bug reports.
