### ISSUE TITLE
Server cannot cleanly stop due to map thread

### ISSUE THREAD

**Issue by RockemRobotics** [bigchadguys/bcgplus#31]
I'm having an issue on my BCG+ server on Nodecraft where it cannot shut down cleanly, getting stuck on the line "Shutting down map thread" (see log). I found some references online to this being associated with an FTB mod but it's not one that is present in this modpack.

[latest(1).log](https://github.com/user-attachments/files/15980024/latest.1.log)

**Comment by jflec** [comment]
I believe it is due to the Selling Bin which is currently being rewritten, in the mean time you should have an option to automatically kill the server after X amount of time, I personally use that method.
