### ISSUE TITLE
Selling price tooltip repeats itself

### ISSUE THREAD

**Issue by kitsunekaze93** [bigchadguys/bcgplus#34]
Every time the game is restarted (save and quit) without restarting the client, another toolbar for pricing gets added
![tooltip_duplicating](https://github.com/bigchadguys/bcgplus/assets/20990827/efab39e1-d58b-434e-b042-5fe59d14d725)
![tooltip_duplicating_2](https://github.com/bigchadguys/bcgplus/assets/20990827/03f0ac93-b0f8-4398-991c-849919ab6810)

**Comment by jflec** [comment]
Will update Selling Bin ASAP.
