### ISSUE TITLE
Addons

### ISSUE THREAD

**Issue by Leightsss** [bigchadguys/bcgplus#36]
It will be very helpful to add another set of datapacks/resourcepacks such as Ascension Megamons for mega evolutions, cobblemon move inspector for poke battle efficiency, Unchained for rewarding hardworkers and Cobblemonrider for obvious reasons.
Could also do well with a resourcepack called Cobbleremodels and other stuff that related to pokemon like cobbletowns, trainers and gyms.
Thank you very much!

**Comment by jflec** [comment]
I appreciate the suggestions! If you want to create a post in the Discord server that is the best place to do it. https://discord.gg/bigchadguys
