### ISSUE TITLE
I cannot find a way to get rid of "death beacons"

### ISSUE THREAD

**Issue by Cybernetic-Fox** [bigchadguys/bcgplus#38]
![beam question](https://github.com/user-attachments/assets/63e7ae20-df57-46b4-88ee-91b874439a79)

I cannot find a way to get rid of these beacons within this modpack. I really would like an urgent response because I personally find this infuriating after spending hours looking and reading mod descriptions to disable this. Please and thankyou to ANYONE who will respond at all. (I mean it, ty for the modpack too)

**Comment by RockemRobotics** [comment]
M is the default keybind for JourneyMap. Inside JourneyMap you can right click on waypoints (including death waypoints) to delete them. You can also click the diamond shaped icon at the bottom (or press the right bracket button ']') to see all of your waypoints and enable/disable/edit/delete them there.

**Comment by Cybernetic-Fox** [comment]
Thankyou so much. I had no idea what JourneyMap was. The majority of my confusion was also because it kept popping up on the FTB Chunks map. Thanks!
