### ISSUE TITLE
Lag Spikes

### ISSUE THREAD

**Issue by jayjuking** [bigchadguys/bcgplus#4]
I am currently experiencing lag spikes every 4-6 seconds, i capped my frame rate to 120fps and every 4-6 seconds it would spike to 70-80 something fps. I have tried using Java arguments executables and all the other methods. I've only experienced these lag spikes for this mod pack, every other modpack/ minecraft versions i play (lunar client), the game runs smoothly. I believe it might be a modpack problem but i don't know. I experience these spikes in singleplayer and multiplayer (with essentials mod) with my friends. I'm the only one experiencing these lag spikes so please help...

My system requirements:
CPU: Ryzen 5600H
GPU: RTX 3050
RAM: 16GB

**Comment by jflec** [comment]
Open up a ticket in the [Discord](https://www.discord.gg/bigchadguys) it'll be much easier to help you there.

This issues page is dedicated towards bug reports.
