### ISSUE TITLE
2.5.0 Leaving and Rejoining a world causes "Sell ##x for #x Emeralds" to duplicate

### ISSUE THREAD

**Issue by jackperry2187** [bigchadguys/bcgplus#42]
- Joined a singleplayer world, hover over any sellable item, shows correctly in tooltip as "Sell ##x for #x Emeralds"
- Leave world and rejoin, hover over any sellable item
- Shows up twice in tooltip, and if you repeat the leave -> rejoin cycle it shows up that many times
- Can be fixed by completely closing and reopening the game, i.e. seemingly resetting the counter to 1, but that isn't great

![image](https://github.com/user-attachments/assets/06e090d7-080f-482b-b72d-b0ae30290c82)

**Comment by jflec** [comment]
Fixed in 2.9.0+
