### ISSUE TITLE
FTB MOD CHECK don't work 

### ISSUE THREAD

**Issue by Helionee** [bigchadguys/bcgplus#54]
Hi, i dowloaded all the mod an added them into the mod folder but im still in the FTB mod check , i did restart the modpack and everything but still nothing, im just blocked on the check ( sorry for my bad vocabulary english is not my first language )

**Comment by jflec** [comment]
The check is purely based off the mods folder, there is no bug, just double check you have all of them. It also checks for a handful of non FTB mods.
