### ISSUE TITLE
Selling Bin Issue

### ISSUE THREAD

**Issue by IEMJustin** [bigchadguys/bcgplus#56]
Current Version: BCG+ 2.8.0
 
I accidentally found a glitch that allows the users to bypass the wait time for selling items.

To Reproduce
- Place selling bin down
- Place items within selling bin
- Break the selling bin block
- Place the selling bin back down
- Items that were inside the selling bin would be sold for their emerald equivalents (Bypassing the wait times)

**Comment by jflec** [comment]
Fixed in 2.9.0+
