### ISSUE TITLE
Farmer's Delight Knives

### ISSUE THREAD

**Issue by dreamgifter** [bigchadguys/bcgplus#57]
When I try to cut things with Farmer Delight's knives on the cutting board, like cabbage to make 2 cabbage leaves or raw cod to make fillets, it will only let me cut it once with a full durability knife. When I cut and the durability goes down, I am no longer able to use the knife again to cut things. I either have to make a new knife or put Mending on my knife. It happens with both the End's Delight knives and the vanilla Farmer's Delight ones.

**Comment by jflec** [comment]
Fixed in 2.9.2
