### ISSUE TITLE
Mod Version Discrepancies

### ISSUE THREAD

**Issue by Korenn-Kammer** [bigchadguys/bcgplus#59]
My server hosting this modpack has been crashing all day whenever anyone tries to join. Upon reading the crash report, it seems that quite a few mods are out of date and are now conflicting with other mods requiring certain versions of the former mods.

Here is what the crash report says:

> [21:28:07] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.16.5
> [21:28:07] [ForkJoinPool-1-worker-1/WARN]: Mod getittogetherdrops uses the version fabric-1.20-1.3.1 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
> [21:28:07] [ForkJoinPool-1-worker-2/WARN]: Mod oceansdelight uses the version fdrf-fabric-1.0.2-1.20 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fdrf'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
> [21:28:07] [ForkJoinPool-1-worker-2/WARN]: Mod hamsters uses the version fabric-1.0.3-1.20.1 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
> [21:28:08] [ForkJoinPool-1-worker-1/WARN]: Mod xercamusic uses the version fabric-1.20.1-1.0.2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
> [21:28:08] [ForkJoinPool-1-worker-1/WARN]: Mod globalpacks uses the version 1.16.1_fabric which isn't compatible with Loader's extended semantic version format (Could not parse version number component '1_fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
> [21:28:08] [ForkJoinPool-1-worker-2/WARN]: Mod xercapaint uses the version fabric-1.20.1-1.0.1 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
> [21:28:08] [ForkJoinPool-1-worker-2/WARN]: Mod letmedespawn uses the version 1.3.2b which isn't compatible with Loader's extended semantic version format (Could not parse version number component '2b'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
> [21:28:08] [ForkJoinPool-1-worker-1/WARN]: Mod design_decor uses the version 0.4.0b_fabric+1.20.1 which isn't compatible with Loader's extended semantic version format (Could not parse version number component '0b_fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
> [21:28:08] [main/WARN]: Warnings were found!
>  - Mod 'Alloy Forgery' (alloy_forgery) 2.1.2+1.20 recommends version 12.0.0 or later of roughlyenoughitems, which is missing!
> 	 - You should install version 12.0.0 or later of roughlyenoughitems for the optimal experience.
>  - Mod 'Create Enchantment Industry' (create_enchantment_industry) 1.2.16 recommends version 0.5.1-f-build.1335+mc1.20.1 of mod 'Create' (create), but only the wrong version is present: 0.5.1-f-build.1417+mc1.20.1!
> 	 - You should install version 0.5.1-f-build.1335+mc1.20.1 of mod 'Create' (create) for the optimal experience.
>  - Mod 'Debugify' (debugify) 1.20.1+2.0 recommends any 3.x version of yet-another-config-lib, which is missing!
> 	 - You should install any 3.x version of yet-another-config-lib for the optimal experience.
>  - Mod 'Debugify' (debugify) 1.20.1+2.0 recommends any version of modmenu, which is missing!
> 	 - You should install any version of modmenu for the optimal experience.
>  - Mod 'Every Compat' (everycomp) 1.20-2.6.82 recommends any version of sawmill, which is missing!
> 	 - You should install any version of sawmill for the optimal experience.
>  - Mod 'JourneyMapIntegration' (jmi) 1.20.1-0.14-48 recommends version 14 or later of waystones, which is missing!
> 	 - You should install version 14 or later of waystones for the optimal experience.
>  - Mod 'Reacharound' (reacharound) 1.3.0 recommends any version of modmenu, which is missing!
> 	 - You should install any version of modmenu for the optimal experience.

This crashing doesn't seem to happen during Singleplayer worlds, but they have been consistently happening to the server regardless of who tries to join. All players have the up-to-date version of the modpack.

**Comment by jflec** [comment]
The crashes are due to corrupted Selling Bins in the world, you'll need to launch the server with the Bin mod removed to wipe any existing, once that's done you're good to add it back in and play like normal.

**Comment by Korenn-Kammer** [comment]
> The crashes are due to corrupted Selling Bins in the world, you'll need to launch the server with the Bin mod removed to wipe any existing, once that's done you're good to add it back in and play like normal.

I tried removing the Selling Bins mod from the pack and then joined the world. It then gave me an error saying that it is missing a mod registry and that I can't join unless that mod is there. How can I do this?

**Comment by jflec** [comment]
You need to remove the mod from your client as well before joining

**Comment by Korenn-Kammer** [comment]
I did remove it from the mods folder on my computer. I am not sure how to remove it elsewhere.

**Comment by jflec** [comment]
It should be removed from your server files as well, how are you hosting?

**Comment by Korenn-Kammer** [comment]
The server is hosted on Aternos. I don't know how to access the files on there.

**Comment by TastyUnicornFart** [comment]
I had the same problem on SP, removing the mod from the folder and deleting the selling_bin.dat helped me.
The file mentioned can be found in the world folder -> data -> sellingbin. Not sure how it would look for server files, hope this helps in some way.

**Comment by jflec** [comment]
Aternos is a bit more difficult as it doesn't allow for edits to be made to the pack, are you able to downgrade server files as a whole?

**Comment by Korenn-Kammer** [comment]
While I say "my server," I do share the server with a friend. She has granted me access to the server for the most part, but I don't think she gave me access to view the files. When she comes back online, I can share these details with her and see if she can do something. I'll update when that happens. Thanks for the tips!

**Comment by Korenn-Kammer** [comment]
Alright, the issue is fixed. We put the server onto another host, took out Selling Bins, and put it back on Aternos. It nows runs like normal. Thanks for the advice!
