### ISSUE TITLE
Ticking on pause

### ISSUE THREAD

**Issue by VoidMage236** [bigchadguys/bcgplus#61]
Hi I have no idea what inventory it is talking about, but a inventory keeps causing a ticking crash. Would you what might be the cause?
[crash-2024-10-10_15.43.31-server.txt](https://github.com/user-attachments/files/17333554/crash-2024-10-10_15.43.31-server.txt)

**Comment by eli-wynn** [comment]
Hey I'm experiencing the exact same issue in both an aternos server and when I opened the world in a solo 
[crash-2024-10-10_15.43.31-server.txt](https://github.com/user-attachments/files/17334131/crash-2024-10-10_15.43.31-server.txt)

**Comment by jflec** [comment]
Fixed in 2.9.3+
