### ISSUE TITLE
Recipe Favourites not working when you Press the A Button, and Solution...

### ISSUE THREAD

**Issue by Krazyman999** [bigchadguys/bcgplus#64]
Problem... Recipe Favourites wont work, when you Press the A Button
Solution.. Fix in EMI Setting, in-game, EMI Settings in Inventory Menu at bottom Left.

Fixing it...
1. Start BCG Plus modpack
2. Open Inventory
3. Click on EMI on bottom left
4. Scroll down to... Left Sidebar
5. Click on Pages + ... select Favourites ... this will add a new Favourites in the Left Side
6. Margins Top ... change it to 60 ... this will lower your new Favourites, below the other icons that are already there

Fixed...

**Comment by jflec** [comment]
Implemented in 2.10.0
