### ISSUE TITLE
"Create: Crafts and Additions" and "Create: : deco" Zinc Sheet not interchangeable in crafting and share crafting recipe.

### ISSUE THREAD

**Issue by RolandReff** [bigchadguys/bcgplus#7]
BGC+ 1.1.15
The two Zinc Sheets from "Create: Crafts and Additions" and "Create: : deco" share method of creation (Zinc Ingot in the Create Press), which becomes the Zinc Sheets from "create:deco". This would not be a problem if they were interchangeable in crafting, which they are not. Locking players out of the option to use the "Create: Crafts and Additions" electricity suit.

**Comment by jflec** [comment]
Sorry for the late reply! Will get this fixed next update, thank you for letting me know! 🫡
