### ISSUE TITLE
[Let's Do] Candlelight's Gold Ring not applying luck 2 buff when in ring or 2nd body slot

### ISSUE THREAD

**Issue by xKiva** [bigchadguys/bcgplus#8]
Even with the change which allows it to be put into the ring slot, the effect is only active when worn as the main chest piece,

**Comment by jflec** [comment]
Sorry for the late reply. Did some digging and it appears this is intending behavior from the mod developer until they figure out proper balancing. I'll see if I can find a workaround that abides by their licensing. 🫡
