### ISSUE TITLE
Version Changelogs Missing

### ISSUE THREAD

**Issue by DQuinn97** [bigchadguys/bcgplus#9]
I have noticed that with a recent update all the version releases that got a later hotfix release have been removed from the version list. With this, the changelog we all loved to read also disappeared for those versions. Those changelogs contained a lot of information and were incredibly well structured so we'd immediately know what's new, they were awesome.

Would it be possible to re-add the changelogs for those versions (or at least 1.1.15 and above, I doubt many people are still playing before 1.1.14?) to their hotfix version changelog, so we know what's been changed since the last version?

Screenshots for visual information (yes, I know it's curseforge despite your warnings, don't mind that part please).

![Annotation 2024-04-08 113803](https://github.com/bigchadguys/bcgplus/assets/44023796/070573c3-05d1-4be8-b4a7-48a27f6959b1)
![Annotation 2024-04-08 114023](https://github.com/bigchadguys/bcgplus/assets/44023796/c7aeb9c8-7f83-4125-956a-26933c914115)

**Comment by jflec** [comment]
Will edit onto 1.1.16HF.
